### ISSUE TITLE
label

### ISSUE THREAD

**Issue by exxistance** [mctenthij/hortiradar#1]
Labels zijn nu niet variabel, is er de optie dit te flexibiliseren?
{"counts":"12345","keyword":"abcd"} nu moet iedereen zijn eigen conversie bouwen om te komen tot: {"name":"abcd","value":"12345"}

Overigens regelmatig geen response van de api

**Comment by rahiel** [comment]
> Labels zijn nu niet variabel, is er de optie dit te flexibiliseren?
> {"counts":"12345","keyword":"abcd"} nu moet iedereen zijn eigen conversie bouwen om te komen tot: {"name":"abcd","value":"12345"}

Labels worden niet variabel, we gaan ervan uit dat gebruikers zelf hun data kunnen omvormen tot hoe zij het willen.

> Overigens regelmatig geen response van de api

De huidige server heeft het erg zwaar omdat er constant nieuwe tweets bijkomen. Antwoorden van de API zijn dus heel traag.
